# -------------------------------------------------------------------
# Install required packages from GitHub
# -------------------------------------------------------------------
# rfcipPRF:
#   - Core utilities and PRF-specific helpers used across the analysis
# indexDesignWindows:
#   - Replication package for the PRF index historical-window redesign study
#
# force = TRUE ensures the latest version is installed
# upgrade = "never" avoids upgrading CRAN dependencies (for reproducibility)
devtools::install_github("ftsiboe/rfcipPRF", force = TRUE, upgrade = "never",auth_token = Sys.getenv("rfcipPRF_TOKEN", unset = NA))
#devtools::install_github("ftsiboe/indexDesignWindows", force = TRUE, upgrade = "never")
devtools::document()

# -------------------------------------------------------------------
# Download PRF Index Redesign Outputs
# -------------------------------------------------------------------
# These files contain the redesigned PRF indices constructed using
# historical windows ranging from 5 to 60 years (1-year increments).
#
# Generated by:
#   - data-raw/scripts/002_render_index.R  (index construction)
#   - data-raw/scripts/003_render_rate.R   (rate & payment factor development)
#
# Files are downloaded into:
#   data-raw/releases/redesigns/
get_study_releases(
  owner        = "ftsiboe",
  output_directory = "data-raw/releases/redesigns",
  repository   = "indexDesignWindows",
  release_tag  = "redesigns"
)


# -------------------------------------------------------------------
# Download Baseline Analysis Outputs
# -------------------------------------------------------------------
# These files contain baseline diagnostics evaluating each index redesign
# against the current (official) PRF index design.
#
# Generated by:
#   - data-raw/scripts/004_baseline_analysis.R
#
# Files are downloaded into:
#   data-raw/releases/baseline/
get_study_releases(
  owner            = "ftsiboe",
  output_directory = "data-raw/releases/baseline",
  repository       = "indexDesignWindows",
  release_tag      = "baseline"
)


# -------------------------------------------------------------------
# Download Statistical Threshold Diagnostics
# -------------------------------------------------------------------
# These files contain statistical threshold diagnostics used to assess
# stability, balance, and performance across alternative historical
# window lengths.
#
# Generated by:
#   - data-raw/scripts/005_statistical_threshold_analysis.R
#
# Files are downloaded into:
#   data-raw/releases/statistical_threshold/
get_study_releases(
  owner            = "ftsiboe",
  output_directory = "data-raw/releases/statistical_threshold/",
  repository       = "indexDesignWindows",
  release_tag      = "statistical_threshold"
)
