# -------------------------------------------------------------------
# Install required packages from GitHub
# -------------------------------------------------------------------
# rfcipPRF:
#   - Core utilities and PRF-specific helpers used across the analysis
# indexDesignWindows:
#   - Replication package for the PRF index historical-window redesign study
#
# force = TRUE ensures the latest version is installed
# upgrade = "never" avoids upgrading CRAN dependencies (for reproducibility)
# devtools::install_github("ftsiboe/rfcipPRF", force = TRUE, upgrade = "never",auth_token = Sys.getenv("rfcipPRF_TOKEN", unset = NA))
#devtools::install_github("ftsiboe/indexDesignWindows", force = TRUE, upgrade = "never")
devtools::document()
# -------------------------------------------------------------------
# Data
# -------------------------------------------------------------------
source("data-raw/scripts/001_workflow_data.R")

# -------------------------------------------------------------------
# Download PRF Index Redesign Outputs
# -------------------------------------------------------------------
# These files contain the redesigned PRF indices constructed using
# historical windows ranging from 5 to 60 years (1-year increments).
#
# Generated by:
#   - data-raw/scripts/002_render_index.R  (index construction)
#   - data-raw/scripts/003_render_rate.R   (rate & payment factor development)
#
# Files are downloaded into:
#   data-raw/releases/redesigns/

# dir.create("data-raw/releases/redesigns", recursive = TRUE, showWarnings = FALSE)
#
# get_study_releases(
#   owner        = "ftsiboe",
#   output_directory = "data-raw/releases/redesigns",
#   repository   = "indexDesignWindows",
#   release_tag  = "redesigns"
# )

# -------------------------------------------------------------------
# Download Baseline Analysis Outputs
# -------------------------------------------------------------------
# These files contain baseline diagnostics evaluating each index redesign
# against the current (official) PRF index design.
#
# Generated by:
#   - data-raw/scripts/004_baseline_analysis.R
#
# Files are downloaded into:
#   data-raw/releases/baseline/

dir.create("data-raw/releases/baseline", recursive = TRUE, showWarnings = FALSE)

get_study_releases(
  owner            = "ftsiboe",
  output_directory = "data-raw/releases/baseline",
  repository       = "indexDesignWindows",
  release_tag      = "baseline"
)

# -------------------------------------------------------------------
# Download alternative Analysis Outputs
# -------------------------------------------------------------------
# These files contain alternative diagnostics evaluating each index redesign
# against the current (official) PRF index design.
#
# Generated by:
#   - data-raw/scripts/004_baseline_analysis.R
#
# Files are downloaded into:
#   data-raw/releases/alternative/

dir.create("data-raw/releases/alternative", recursive = TRUE, showWarnings = FALSE)

get_study_releases(
  owner            = "ftsiboe",
  output_directory = "data-raw/releases/alternative",
  repository       = "indexDesignWindows",
  release_tag      = "alternative"
)

# -------------------------------------------------------------------
# Precipitation Trend Diagnostics
# -------------------------------------------------------------------

piggyback::pb_download(
  file = "county_precipitation_trend.rds",
  dest = "data-raw/output",
  repo = "ftsiboe/indexDesignWindows",
  tag  = "other",
  overwrite = TRUE)


